food_court/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('inventories/', include('inventories.urls')),
    path('orders/', include('orders.urls')),
    path('admin/', admin.site.urls),
]

inventories/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
]

orders/urls.py
from django.urls import path

from . import views

app_name = 'orders'
urlpatterns = [
    path('<str:order_id>/', views.OrderView, name='order'),
    path('', views.OrderSubmit, name='order_submit'),
]

inventories/models.py
from uuid import uuid4

from django.db import models


# Create your models here.
class Inventory(models.Model):
    id = models.UUIDField(primary_key=True, null=False, db_index=True, unique=True, editable=False, default=uuid4)
    title = models.CharField(max_length=200)
    unit_price = models.DecimalField(decimal_places=2, max_digits=60)
    qty = models.IntegerField(default=1)
    created = models.DateTimeField(auto_now_add=True, null=False)
    updated = models.DateTimeField(auto_now=True, null=False)

    def __str__(self):
        return self.title + " " + str(self.id)

orders/models.py
from uuid import uuid4

from django.db import models


# Create your models here.
class Order(models.Model):
    id = models.UUIDField(primary_key=True, null=False, db_index=True, unique=True, editable=False, default=uuid4)
    date = models.DateTimeField()
    items = models.ManyToManyField("inventories.Inventory", related_name='menu_items')
    created = models.DateTimeField(auto_now_add=True, null=False)
    updated = models.DateTimeField(auto_now=True, null=False)

    def __str__(self):
        return str(self.id)

inventories/views.py
from django.views import generic

from inventories.models import Inventory


# Create your views here.
class IndexView(generic.ListView):
    template_name = 'index.html'
    context_object_name = 'inventory_list'

    def get_queryset(self):
        return Inventory.objects.filter(qty__gte=1).order_by('-created')

orders/views.py
import datetime

from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.urls import reverse

from orders.models import Order


# Create your views here.
def OrderView(request, order_id):
    order_data = get_object_or_404(Order, pk=order_id)
    return render(request, 'order_details.html', {'order_data': order_data})


def OrderSubmit(request):
    raw_data = request.POST.copy()
    del raw_data["csrfmiddlewaretoken"]
    order_date = datetime.datetime.strptime(raw_data.pop("order_date")[0], "%d/%m/%Y").date()
    item_ids = [k for k,v in raw_data.items() if v == 'true']
    new_order = Order.objects.create(date=order_date)
    new_order.items.add(*item_ids)
    return HttpResponseRedirect(reverse('orders:order', args=(new_order.id,)))

inventories/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Food court</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css"
          integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <!--  jQuery -->
    <script type="text/javascript" src="https://code.jquery.com/jquery-1.11.3.min.js"></script>
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js"></script>

    <!-- Isolated Version of Bootstrap, not needed if your site already uses Bootstrap -->
    <link rel="stylesheet" href="https://formden.com/static/cdn/bootstrap-iso.css"/>

    <!-- Bootstrap Date-Picker Plugin -->
    <script type="text/javascript"
            src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.4.1/js/bootstrap-datepicker.min.js"></script>
    <link rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.4.1/css/bootstrap-datepicker3.css"/>
</head>
<body>
<div class="container">
    <div class="row pt-5 pb-2">
        <h3 class="m-auto">Food Ordering System</h3>
    </div>
    <div class="row">
        <table class="table">
            <form action="{% url 'orders:order_submit' %}" method="post">
                {% csrf_token %}
                <div class="col-12 pb-5">
                    <label class="font-weight-bold">Order date</label>
                    <input class="form-control" id="order_date" name="order_date" placeholder="DD/MM/YYY" type="text"/>
                </div>
                <thead class="thead-dark">
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Menu</th>
                    <th scope="col">price</th>
                    <th scope="col"></th>
                </tr>
                </thead>
                <tbody name="tbody">

                {% if inventory_list %}
                {% for item in inventory_list %}
                <tr>
                    <th data-id="{{ item.id }}" scope="row">{{forloop.counter}}</th>
                    <td>{{ item.title }}</td>
                    <td>${{ item.unit_price }}</td>
                    <td><input class="item_checkbox" data-price="{{ item.unit_price }}" name="{{ item.id }}"
                               id="{{ item.id }}" type="checkbox"
                               aria-label="Checkbox" value="false"></td>
                </tr>
                {% endfor %}
                <tr>
                    <th scope="row"></th>
                    <td class="text-right"><b>Total:</b></td>
                    <td><b id="total_order_price">$0</b></td>
                    <td><input type="submit" class="btn btn-dark" value="Place Order"/></td>
                </tr>
                {% else %}
                <p>No items are available.</p>
                {% endif %}

                </tbody>
            </form>
        </table>
    </div>
</div>

<script type="text/javascript">
$(document).ready(function(){
var date_input=$('#order_date'); //our date input has the name "date"
      var container=$('.bootstrap-iso form').length>0 ? $('.bootstrap-iso form').parent() : "body";
      var options={
        format: 'dd/mm/yyyy',
        container: container,
        todayHighlight: true,
        autoclose: true,
        startDate: "0d",
      };
      date_input.datepicker(options);
      date_input.datepicker('setDate', 'now');

  $('.item_checkbox').change(function() {
        $(this).val(this.checked);
        var total_price = 0;
        $('.item_checkbox').each(function () {
            if($(this).is(':checked')){
                total_price = total_price + parseFloat($(this).data("price"));
            }
        });
        $("#total_order_price").html("$" + total_price)
    });
});

</script>


</body>
</html>

orders/templates/order_details.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Food court</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css"
          integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script type="text/javascript" src="https://code.jquery.com/jquery-1.11.3.min.js"></script>
</head>
<body>

<div class="container">
    <div class="row pt-5 pb-2">
        <h3 class="m-auto">Order Details</h3>
    </div>
    <div class="row pb-4">
        <p class="m-auto">Order Date: {{ order_data.date|date:"M d, Y" }}</p>
    </div>
    <div class="row">
            <table class="table">
                <thead class="thead-dark">
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Menu</th>
                    <th scope="col">qty</th>
                    <th scope="col">price</th>
                </tr>
                </thead>
                <tbody>

                {% if order_data %}
                {% for item in order_data.items.all %}
                <tr>
                    <th data-id="{{ item.id }}" scope="row">{{forloop.counter}}</th>
                    <td>{{ item.title }}</td>
                    <td>1</td>
                    <td class="order_unit_price" data-price="{{ item.unit_price }}">${{ item.unit_price }}</td>
                </tr>
                {% endfor %}
                <tr>
                    <th scope="row"></th>
                    <td></td>
                    <td class="text-right"><b>Total:</b></td>
                    <td><b id="total_order_price">$0</b></td>
                </tr>
                {% else %}
                <p>Order id not found.</p>
                {% endif %}

                </tbody>
            </table>
        <div class="row pt-5 pb-2 m-auto">
            <a href="/inventories/" type="submit" class="btn btn-dark">Home</a>
        </div>
    </div>
</div>
<script type="text/javascript">
$(document).ready(function(){
var total_price = 0;
$(".order_unit_price").each(function () {
    total_price = total_price + parseFloat($(this).data("price"));
        });
        $("#total_order_price").html("$" + total_price)
});
</script>

</body>
</html>